---
## File: services.yml - services configuration

- name: Configure consul services
  ansible.builtin.template:
    dest: "{{ consul_configd_path }}/service_{{ service_item.id }}.json"
    src: service.json.j2
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0644"
  with_items: "{{ consul_services }}"
  loop_control:
    loop_var: service_item
  notify:
    - restart consul

- name: Include tasks for *nix services
  ansible.builtin.include_tasks:
    file: services-unix.yml
  when: ansible_os_family != 'Windows'

- name: Include tasks for Windows services
  ansible.builtin.include_tasks:
    file: services-windows.yml
  when: ansible_os_family == 'Windows'

