---
- name: restart_consul.yml | Daemon reload systemd in case the binaries upgraded
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  when: ansible_service_mgr == "systemd"
  listen: 'reload systemd daemon'

- name: restart_consul.yml | restart consul on unix
  ansible.builtin.service:
    name: consul
    state: restarted
  when:
    - ansible_os_family != "Darwin"
    - ansible_os_family != "Windows"
  listen: 'restart consul'

- name: restart_consul.yml | restart consul on Mac
  ansible.builtin.include_tasks: "{{ role_path }}/handlers/restart_consul_mac.yml"
  when: ansible_os_family == "Darwin"
  listen: 'restart consul'

- name: restart_consul.yml | restart consul on Windows
  ansible.builtin.include_tasks: "{{ role_path }}/handlers/restart_consul_windows.yml"
  when: ansible_os_family == "Windows"
  listen: 'restart consul'
