---
- name: Include firewalld
  ansible.builtin.import_tasks: firewalld.yml
  when: "(firewall_disable_firewalld is defined) and not (firewall_disable_firewalld|bool) and firewall_disable_ufw|bool"

- name: Include uwf
  ansible.builtin.import_tasks: uwf.yml
  when: "(firewall_disable_firewalld|bool) and (firewall_disable_ufw is defined) and not (firewall_disable_ufw|bool)"

- name: Setup iptables
  ansible.builtin.import_tasks: iptables.yml
  when: firewall_disable_firewalld|bool and firewall_disable_ufw|bool

- name: Disable other firewalls
  ansible.builtin.import_tasks: disable-other-firewalls.yml
  when: firewall_disable_firewalld|bool or firewall_disable_ufw|bool

...
